include(CMakeFindDependencyMacro)
include("${CMAKE_CURRENT_LIST_DIR}/WebSceneLinuxProfile.cmake")
if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64)$")
  set(WebScene_FOUND FALSE)
  set(WebScene_NOT_FOUND_MESSAGE "This SDK contains Linux x86_64 binaries")
  return()
endif()
# Older native-only profiles predate the explicit compiler fields.
if(NOT DEFINED WebScene_SDK_COMPILER_VERSION)
  set(WebScene_SDK_COMPILER_ID Clang)
  set(WebScene_SDK_COMPILER_VERSION 22.1.1)
  set(WebScene_SDK_CXX_ABI "libc++")
endif()
if(NOT CMAKE_CXX_COMPILER_ID STREQUAL WebScene_SDK_COMPILER_ID OR
   NOT CMAKE_CXX_COMPILER_VERSION VERSION_EQUAL WebScene_SDK_COMPILER_VERSION)
  message(FATAL_ERROR "This SDK requires ${WebScene_SDK_COMPILER_ID} ${WebScene_SDK_COMPILER_VERSION}/${WebScene_SDK_CXX_ABI}; use WebSceneToolchain.cmake")
endif()
find_dependency(Threads)
get_filename_component(WebScene_SDK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
function(_ws_linux_static name file)
  if(NOT EXISTS "${WebScene_SDK_ROOT}/lib/${file}")
    message(FATAL_ERROR "Incomplete Linux SDK: missing ${file}")
  endif()
  add_library(WebScene::${name} STATIC IMPORTED GLOBAL)
  set_target_properties(WebScene::${name} PROPERTIES
    IMPORTED_LOCATION "${WebScene_SDK_ROOT}/lib/${file}"
    INTERFACE_INCLUDE_DIRECTORIES "${WebScene_SDK_ROOT}/include"
    INTERFACE_COMPILE_FEATURES cxx_std_20
    INTERFACE_COMPILE_OPTIONS "-stdlib=${WebScene_SDK_CXX_ABI}"
    INTERFACE_LINK_OPTIONS "-stdlib=${WebScene_SDK_CXX_ABI};LINKER:--gc-sections")
endfunction()
if(NOT TARGET WebScene::Core)
  _ws_linux_static(Core libwebscene_core.a)
  _ws_linux_static(NativeWeb libwebscene_native_web.a)
  _ws_linux_static(_Parser libwebscene_html_parser.a)
  _ws_linux_static(SharedCSS libwebscene_native_web_shared_css.a)
  set_property(TARGET WebScene::NativeWeb PROPERTY INTERFACE_LINK_LIBRARIES "WebScene::Core;Threads::Threads;${CMAKE_DL_LIBS}")
  set_property(TARGET WebScene::_Parser PROPERTY INTERFACE_LINK_LIBRARIES "Threads::Threads;${CMAKE_DL_LIBS};m")
  set_property(TARGET WebScene::SharedCSS PROPERTY INTERFACE_LINK_LIBRARIES "WebScene::NativeWeb;WebScene::_Parser;Threads::Threads;${CMAKE_DL_LIBS}")
  if(WebScene_SDK_WEBGPU)
    if(NOT EXISTS "${WebScene_SDK_ROOT}/lib/libwebgpu_dawn.so")
      message(FATAL_ERROR "Incomplete Linux SDK: missing pinned Dawn library")
    endif()
    add_library(WebScene::_Dawn SHARED IMPORTED GLOBAL)
    set_target_properties(WebScene::_Dawn PROPERTIES IMPORTED_LOCATION "${WebScene_SDK_ROOT}/lib/libwebgpu_dawn.so"
      INTERFACE_INCLUDE_DIRECTORIES "${WebScene_SDK_ROOT}/include")
    add_library(WebScene::WebGPU INTERFACE IMPORTED GLOBAL)
    set_target_properties(WebScene::WebGPU PROPERTIES
      INTERFACE_LINK_LIBRARIES "WebScene::Core;WebScene::_Dawn;Threads::Threads;${CMAKE_DL_LIBS}"
      INTERFACE_INCLUDE_DIRECTORIES "${WebScene_SDK_ROOT}/include/graphics")
  endif()
  add_executable(WebScene::Compiler IMPORTED GLOBAL)
  set_property(TARGET WebScene::Compiler PROPERTY IMPORTED_LOCATION "${WebScene_SDK_ROOT}/bin/webscene-uic")
endif()
if(WebScene_SDK_RUNTIME AND NOT TARGET WebScene::Runtime)
  find_dependency(OpenSSL)
  find_dependency(ZLIB)
  _ws_linux_static(_V8 libv8_monolith.a)
  _ws_linux_static(_Media libwebscene_media.a)
  _ws_linux_static(_WebSocket libixwebsocket.a)
  _ws_linux_static(Runtime libwebscene_native_engine.a)
  set_property(TARGET WebScene::_WebSocket PROPERTY INTERFACE_LINK_LIBRARIES "OpenSSL::SSL;OpenSSL::Crypto;ZLIB::ZLIB;Threads::Threads")
  set_property(TARGET WebScene::Runtime PROPERTY INTERFACE_LINK_LIBRARIES
    "WebScene::Core;WebScene::_Media;WebScene::_WebSocket;WebScene::_Parser;WebScene::_V8;WebScene::WebGPU;Threads::Threads;${CMAKE_DL_LIBS};rt;m")
  set(WebScene_RUNTIME_ASSET_DIRECTORY "${WebScene_SDK_ROOT}/runtime")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/WebSceneApplication.cmake")
set(WebScene_FOUND TRUE)
unset(WebScene_NOT_FOUND_MESSAGE)
foreach(component IN LISTS WebScene_FIND_COMPONENTS)
  if(TARGET WebScene::${component})
    set(WebScene_${component}_FOUND TRUE)
  else()
    set(WebScene_${component}_FOUND FALSE)
    if(WebScene_FIND_REQUIRED_${component})
      set(WebScene_FOUND FALSE)
      string(APPEND WebScene_NOT_FOUND_MESSAGE "Component ${component} is not installed in this Linux SDK profile. ")
    endif()
  endif()
endforeach()
