# Deliberate Runtime/hybrid opt-in. Native targets never link these libraries.
if(NOT WEBSCENE_SDK_WEBGPU)
  message(FATAL_ERROR "The Linux Runtime headless profile requires WEBSCENE_SDK_WEBGPU=ON")
endif()
if(NOT WEBSCENE_SDK_CXX_ABI STREQUAL "libstdc++")
  message(FATAL_ERROR "The pinned Linux V8 package uses libstdc++; select WEBSCENE_SDK_CXX_ABI=libstdc++ and Clang 18.1.3")
endif()
if(NOT WEBSCENE_V8_ROOT OR NOT WEBSCENE_V8_OUTPUT_ROOT)
  message(FATAL_ERROR "Supply the pinned WEBSCENE_V8_ROOT and WEBSCENE_V8_OUTPUT_ROOT (V8 15.3.10 / ReleasePartitionAlloc)")
endif()
execute_process(COMMAND "${Python3_EXECUTABLE}" "${WEBSCENE_ROOT}/eng/sdk/verify-linux-v8.py"
  --root "${WEBSCENE_V8_ROOT}" --output "${WEBSCENE_V8_OUTPUT_ROOT}"
  --manifest "${CMAKE_CURRENT_BINARY_DIR}/linux-v8.json"
  COMMAND_ERROR_IS_FATAL ANY)
set(WEBSCENE_NATIVE_ENGINE_STATIC ON CACHE BOOL "Static SDK Runtime component" FORCE)
set(WEBSCENE_NATIVE_ENGINE_ENABLE_V8 ON CACHE BOOL "Explicit Runtime profile" FORCE)
set(WEBSCENE_NATIVE_ENGINE_ENABLE_GRAPHICS ON CACHE BOOL "Runtime offscreen Vulkan" FORCE)
set(WEBSCENE_NATIVE_ENGINE_COMPILED_APPLICATION_MODULE "" CACHE FILEPATH "Applications register their own compiled packages" FORCE)
set(WEBSCENE_V8_POINTER_COMPRESSION ON CACHE BOOL "Pinned V8 ABI" FORCE)
set(WEBSCENE_V8_POINTER_COMPRESSION_SHARED_CAGE ON CACHE BOOL "Pinned V8 ABI" FORCE)
set(WEBSCENE_V8_PARTITION_ALLOC ON CACHE BOOL "Pinned V8 ABI" FORCE)
set(WEBSCENE_V8_DIRECT_HANDLE OFF CACHE BOOL "Pinned V8 ABI" FORCE)
add_subdirectory("${WEBSCENE_ROOT}/experiments/WebScene.NativeEngine.Probe" runtime)
add_library(WebScene::Runtime ALIAS webscene_native_engine)
foreach(target webscene_native_engine webscene_media ixwebsocket)
  if(TARGET ${target})
    target_compile_options(${target} PRIVATE -ffunction-sections -fdata-sections)
    install(TARGETS ${target} ARCHIVE DESTINATION lib)
  endif()
endforeach()
install(FILES "${WEBSCENE_V8_OUTPUT_ROOT}/obj/libv8_monolith.a" DESTINATION lib)
install(FILES "${WEBSCENE_V8_OUTPUT_ROOT}/icudtl.dat" DESTINATION runtime)
if(WEBSCENE_NATIVE_ENGINE_V8_SNAPSHOT STREQUAL "bootstrap")
  install(FILES "${CMAKE_CURRENT_BINARY_DIR}/runtime/webscene_bootstrap_snapshot.bin"
    "${CMAKE_CURRENT_BINARY_DIR}/runtime/webscene_bootstrap_snapshot.meta" DESTINATION runtime)
endif()
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/linux-v8.json" DESTINATION share/webscene/dependencies)
install(FILES "${WEBSCENE_V8_ROOT}/LICENSE" DESTINATION share/licenses/WebScene/V8)
install(FILES "${WEBSCENE_V8_ROOT}/third_party/icu/LICENSE" DESTINATION share/licenses/WebScene/ICU)
# FetchContent variables are defined in the runtime subdirectory. Read the
# populated location rather than assume a producer-specific _deps directory.
FetchContent_GetProperties(webscene_ixwebsocket)
if(webscene_ixwebsocket_SOURCE_DIR)
  install(FILES "${webscene_ixwebsocket_SOURCE_DIR}/LICENSE.txt" DESTINATION share/licenses/WebScene/IXWebSocket)
endif()
