include_guard(GLOBAL)
include(CMakeParseArguments)
# These are build-time inputs, not a second module resolver. Declare all emitted
# bundle chunks/modules, or HTML with local script tags. Existing V8 semantics
# (including dynamic source compilation) are retained for non-declared scripts.
function(webscene_precompile_javascript target)
  cmake_parse_arguments(JS "" "" "SOURCES;MODULES;HTML;DEPENDS" ${ARGN})
  if(JS_UNPARSED_ARGUMENTS OR JS_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "Invalid webscene_precompile_javascript arguments")
  endif()
  if(NOT TARGET "${target}")
    message(FATAL_ERROR "Unknown JavaScript application target: ${target}")
  endif()
  get_target_property(already "${target}" WEBSCENE_PRECOMPILED_JAVASCRIPT)
  if(already)
    message(FATAL_ERROR "Declare all precompiled inputs in one call per application")
  endif()
  if(CMAKE_CROSSCOMPILING)
    message(FATAL_ERROR "Precompiled V8 caches require a matching target-native SDK compiler; cross compilation is not supported yet")
  endif()
  if(NOT TARGET WebScene::Runtime)
    message(FATAL_ERROR "Precompiled JavaScript requires the SDK Runtime component")
  endif()
  if(NOT TARGET WebScene::JavaScriptCompiler)
    message(FATAL_ERROR "The installed SDK has no JavaScript compiler; rebuild/update the SDK")
  endif()
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  set(manifest "{\"schemaVersion\":1,\"inputs\":[]}")
  set(inputs)
  set(index 0)
  foreach(kind classic module html)
    if(kind STREQUAL "classic")
      set(files ${JS_SOURCES})
    elseif(kind STREQUAL "module")
      set(files ${JS_MODULES})
    else()
      set(files ${JS_HTML})
    endif()
    foreach(file IN LISTS files)
      get_filename_component(file "${file}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
      # CMake JSON has no quote primitive. Escape all JSON string metacharacters.
      string(REPLACE "\\" "\\\\" escaped "${file}")
      string(REPLACE "\"" "\\\"" escaped "${escaped}")
      string(REPLACE "\n" "\\n" escaped "${escaped}")
      string(REPLACE "\r" "\\r" escaped "${escaped}")
      string(REPLACE "\t" "\\t" escaped "${escaped}")
      string(JSON manifest SET "${manifest}" inputs ${index} "{\"kind\":\"${kind}\",\"path\":\"${escaped}\"}")
      math(EXPR index "${index}+1")
      list(APPEND inputs "${file}")
    endforeach()
  endforeach()
  if(index EQUAL 0)
    message(FATAL_ERROR "Precompiled JavaScript requires SOURCES, MODULES or HTML")
  endif()
  set(base "${CMAKE_CURRENT_BINARY_DIR}/${target}_javascript")
  file(GENERATE OUTPUT "${base}.json" CONTENT "${manifest}\n")
  add_custom_command(OUTPUT "${base}.cpp"
    COMMAND "${Python3_EXECUTABLE}" "${WebScene_SDK_ROOT}/share/webscene/tools/precompile_javascript.py"
      --compiler "$<TARGET_FILE:WebScene::JavaScriptCompiler>"
      --manifest "${base}.json" --output "${base}.cpp" --depfile "${base}.d"
    DEPENDS ${inputs} ${JS_DEPENDS} WebScene::JavaScriptCompiler "${base}.json"
      "${WebScene_SDK_ROOT}/share/webscene/tools/precompile_javascript.py"
    DEPFILE "${base}.d"
    COMMENT "Precompiling ${target} JavaScript with the matching WebScene V8 runtime"
    VERBATIM)
  target_sources("${target}" PRIVATE "${base}.cpp")
  target_link_libraries("${target}" PRIVATE WebScene::Runtime)
  set_property(TARGET "${target}" PROPERTY WEBSCENE_PRECOMPILED_JAVASCRIPT TRUE)
endfunction()
