# Linux SDK producer. Runtime is an explicit additional component; Native
# consumers stay independent of V8. Existing macOS production is unchanged.
if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64)$")
  message(FATAL_ERROR "The Linux SDK profile currently targets x86_64")
endif()
if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  message(FATAL_ERROR "Linux SDK production requires a pinned Clang toolchain")
endif()
if(CMAKE_CXX_COMPILER_VERSION VERSION_EQUAL "18.1.3")
  set(_ws_default_abi "libstdc++")
elseif(CMAKE_CXX_COMPILER_VERSION VERSION_EQUAL "22.1.1")
  set(_ws_default_abi "libc++")
else()
  message(FATAL_ERROR "Use Clang 18.1.3/libstdc++ or the existing LLVM 22.1.1/libc++ native profile")
endif()
set(WEBSCENE_SDK_CXX_ABI "${_ws_default_abi}" CACHE STRING "Pinned SDK C++ ABI")
if(NOT WEBSCENE_SDK_CXX_ABI STREQUAL _ws_default_abi)
  message(FATAL_ERROR "Compiler ${CMAKE_CXX_COMPILER_VERSION} requires ${_ws_default_abi} for this SDK profile")
endif()
add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-stdlib=${WEBSCENE_SDK_CXX_ABI}>")
add_link_options("$<$<LINK_LANGUAGE:CXX>:-stdlib=${WEBSCENE_SDK_CXX_ABI}>")
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
# Retain the qualified headless producer's earlier option spelling.
if(DEFINED WEBSCENE_SDK_ENABLE_WEBGPU AND NOT DEFINED WEBSCENE_SDK_WEBGPU)
  set(WEBSCENE_SDK_WEBGPU "${WEBSCENE_SDK_ENABLE_WEBGPU}" CACHE BOOL "Include pinned Dawn/Vulkan support")
endif()
option(WEBSCENE_SDK_WEBGPU "Include pinned Dawn/Vulkan native authoring support" ON)
option(WEBSCENE_SDK_RUNTIME "Include the optional JavaScript Runtime component" OFF)
set(BUILD_TESTING OFF CACHE BOOL "Validate through installed SDK consumers" FORCE)
set(WEBSCENE_NATIVE_WEB_SDK_BUILD ON)
get_filename_component(WEBSCENE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../.." ABSOLUTE)
find_package(Threads REQUIRED)
add_subdirectory("${WEBSCENE_ROOT}/src/WebScene.NativeWeb" native-web)
target_link_libraries(webscene_native_web PUBLIC Threads::Threads ${CMAKE_DL_LIBS})
target_link_libraries(webscene_native_web_shared_css PUBLIC Threads::Threads ${CMAKE_DL_LIBS})
foreach(target webscene_core webscene_native_web webscene_native_web_shared_css)
  target_compile_options(${target} PRIVATE -ffunction-sections -fdata-sections)
endforeach()
add_library(WebScene::Core ALIAS webscene_core)
add_library(WebScene::NativeWeb ALIAS webscene_native_web)
add_library(WebScene::SharedCSS ALIAS webscene_native_web_shared_css)
add_executable(WebScene::Compiler ALIAS webscene-uic)
set_target_properties(webscene-uic PROPERTIES INSTALL_RPATH "$ORIGIN/../lib")
install(TARGETS webscene_core webscene_native_web webscene_native_web_shared_css ARCHIVE DESTINATION lib)
install(TARGETS webscene-uic RUNTIME DESTINATION bin)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/native-web/parser/release/libwebscene_html_parser.a" DESTINATION lib)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
execute_process(COMMAND "${Python3_EXECUTABLE}" "${WEBSCENE_ROOT}/eng/sdk/header-closure.py" "${WEBSCENE_ROOT}"
  OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/sdk-headers.cmake" COMMAND_ERROR_IS_FATAL ANY)
include("${CMAKE_CURRENT_BINARY_DIR}/sdk-headers.cmake")
if(WEBSCENE_SDK_WEBGPU)
  set(WEBSCENE_GRAPHICS_COMPONENTS dawn)
  include("${WEBSCENE_ROOT}/eng/graphics/GraphicsDependencies.cmake")
  add_library(webscene_sdk_webgpu INTERFACE)
  target_include_directories(webscene_sdk_webgpu INTERFACE "${WEBSCENE_ROOT}/experiments/WebScene.NativeEngine.Probe/native/graphics")
  target_link_libraries(webscene_sdk_webgpu INTERFACE webscene_core dawn::webgpu_dawn Threads::Threads)
  add_library(WebScene::WebGPU ALIAS webscene_sdk_webgpu)
  install(DIRECTORY "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/include/" DESTINATION include)
  install(FILES "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/lib/libwebgpu_dawn.so" DESTINATION lib)
  install(DIRECTORY "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/licenses/" DESTINATION share/licenses/WebScene/Dawn)
  install(FILES "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/webscene-graphics-package.json"
    "${WEBSCENE_ROOT}/eng/graphics/dependencies.lock.json" DESTINATION share/webscene/dependencies)
endif()
if(WEBSCENE_SDK_RUNTIME)
  include("${CMAKE_CURRENT_LIST_DIR}/WebSceneLinuxRuntime.cmake")
endif()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/WebSceneLinuxProfile.cmake"
  "set(WebScene_SDK_PLATFORM Linux)\nset(WebScene_SDK_PROCESSOR x86_64)\nset(WebScene_SDK_WEBGPU ${WEBSCENE_SDK_WEBGPU})\nset(WebScene_SDK_RUNTIME ${WEBSCENE_SDK_RUNTIME})\nset(WebScene_SDK_COMPILER_ID ${CMAKE_CXX_COMPILER_ID})\nset(WebScene_SDK_COMPILER_VERSION ${CMAKE_CXX_COMPILER_VERSION})\nset(WebScene_SDK_CXX_ABI \"${WEBSCENE_SDK_CXX_ABI}\")\n")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/WebSceneLinuxProfile.cmake" DESTINATION lib/cmake/WebScene)
install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/cmake/" DESTINATION lib/cmake/WebScene)
include(CMakePackageConfigHelpers)
write_basic_package_version_file("${CMAKE_CURRENT_BINARY_DIR}/WebSceneConfigVersion.cmake"
  VERSION ${PROJECT_VERSION} COMPATIBILITY SameMinorVersion)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/WebSceneConfigVersion.cmake" DESTINATION lib/cmake/WebScene)
install(FILES "${WEBSCENE_ROOT}/LICENSE" DESTINATION share/licenses/WebScene)
