if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  include("${CMAKE_CURRENT_LIST_DIR}/WebSceneLinuxConfig.cmake")
  return()
endif()
include_guard(GLOBAL)
if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/WebSceneLinuxProfile.cmake")
  include("${CMAKE_CURRENT_LIST_DIR}/WebSceneLinuxConfig.cmake")
  return()
endif()
get_filename_component(_ws_prefix "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
include("${CMAKE_CURRENT_LIST_DIR}/WebSceneMacOSProfile.cmake")
webscene_require_macos_profile()
function(_ws_static name filename)
  add_library(WebScene::${name} STATIC IMPORTED GLOBAL)
  set_target_properties(WebScene::${name} PROPERTIES
    IMPORTED_LOCATION "${_ws_prefix}/lib/${filename}"
    INTERFACE_INCLUDE_DIRECTORIES "${_ws_prefix}/include"
    INTERFACE_COMPILE_FEATURES cxx_std_20)
endfunction()
_ws_static(Core libwebscene_core.a)
_ws_static(NativeWeb libwebscene_native_web.a)
set_property(TARGET WebScene::NativeWeb PROPERTY INTERFACE_LINK_LIBRARIES WebScene::Core)
_ws_static(_Parser libwebscene_html_parser.a)
_ws_static(SharedCSS libwebscene_native_web_shared_css.a)
set_property(TARGET WebScene::SharedCSS PROPERTY INTERFACE_LINK_LIBRARIES "WebScene::NativeWeb;WebScene::_Parser;iconv")
add_library(WebScene::_Dawn SHARED IMPORTED GLOBAL)
set_target_properties(WebScene::_Dawn PROPERTIES
  IMPORTED_LOCATION "${_ws_prefix}/lib/libwebgpu_dawn.dylib"
  INTERFACE_INCLUDE_DIRECTORIES "${_ws_prefix}/include")
add_library(WebScene::WebGPU INTERFACE IMPORTED GLOBAL)
set_property(TARGET WebScene::WebGPU PROPERTY INTERFACE_LINK_LIBRARIES
  "WebScene::Core;WebScene::_Dawn;-framework Foundation;-framework IOSurface;-framework CoreVideo;-framework Metal")
set_property(TARGET WebScene::WebGPU PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${_ws_prefix}/include/graphics")
_ws_static(_Media libwebscene_media.a)
_ws_static(_WebSocket libixwebsocket.a)
_ws_static(_V8 libv8_monolith.a)
_ws_static(Runtime libwebscene_native_engine.a)
set_property(TARGET WebScene::Runtime PROPERTY INTERFACE_LINK_LIBRARIES
 "WebScene::Core;WebScene::_Media;WebScene::_WebSocket;WebScene::_Parser;WebScene::_V8;WebScene::WebGPU;iconv;z;-framework Security;-framework CoreFoundation;-framework AVFoundation;-framework CoreMedia;-framework CoreVideo;-framework Foundation;-framework IOSurface")
add_executable(WebScene::Compiler IMPORTED GLOBAL)
set_property(TARGET WebScene::Compiler PROPERTY IMPORTED_LOCATION "${_ws_prefix}/bin/webscene-uic")
set(WebScene_SDK_ROOT "${_ws_prefix}")
include("${CMAKE_CURRENT_LIST_DIR}/WebSceneApplication.cmake")

if(EXISTS "${_ws_prefix}/bin/webscene-jsc")
  add_executable(WebScene::JavaScriptCompiler IMPORTED GLOBAL)
  set_property(TARGET WebScene::JavaScriptCompiler PROPERTY IMPORTED_LOCATION "${_ws_prefix}/bin/webscene-jsc")
  set(WebScene_PrecompiledJavaScript_SUPPORTED TRUE)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/WebScenePrecompiledJavaScript.cmake")
