# Included only by installed Linux profiles that explicitly record libstdc++.
# Never reinterpret a 22.1.1/libc++ archive as this profile.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
function(_ws_linux_compiler output fallback environment_name)
  if(DEFINED ${output} AND NOT "${${output}}" STREQUAL "")
    set(candidate "${${output}}")
  elseif(NOT "$ENV{${environment_name}}" STREQUAL "")
    set(candidate "$ENV{${environment_name}}")
  else()
    set(candidate "${fallback}")
  endif()
  if(IS_ABSOLUTE "${candidate}")
    if(NOT EXISTS "${candidate}")
      message(FATAL_ERROR "Compiler not found: ${candidate}")
    endif()
    set(resolved "${candidate}")
  else()
    find_program(resolved NAMES "${candidate}" REQUIRED NO_CACHE)
  endif()
  set(${output} "${resolved}" CACHE FILEPATH "Installed SDK compiler" FORCE)
endfunction()
_ws_linux_compiler(CMAKE_C_COMPILER clang-18 CC)
_ws_linux_compiler(CMAKE_CXX_COMPILER clang++-18 CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} -stdlib=libstdc++")
