#!/usr/bin/env python3
"""Generate native and managed CSS metadata from the checked-in JSON catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "experiments/WebScene.NativeEngine.Probe/native/css_property_metadata.json"
DEFAULT_OUTPUT = ROOT / "experiments/WebScene.NativeEngine.Probe/native/generated/webscene_css_property_metadata.inc"
DEFAULT_NATIVE_SUPPORTED_OUTPUT = (
    ROOT / "experiments/WebScene.NativeEngine.Probe/native/generated/webscene_css_supported_properties.inc")
DEFAULT_MANAGED_OUTPUT = ROOT / "src/WebScene.Css/CssPropertyMetadata.Generated.cs"
ALLOWED_MASKS = {
    "inline_top", "inline_right", "inline_bottom", "inline_left",
    "inline_margin", "inline_padding", "inline_border", "inline_gap", "inline_overflow",
}


class Catalog:
    def __init__(
        self,
        properties: list[dict[str, object]],
        managed_known_properties: list[str],
        supported_property_extras: list[str],
    ) -> None:
        self.properties = properties
        self.managed_known_properties = managed_known_properties
        self.supported_property_extras = supported_property_extras


def _load_name_list(payload: dict[str, object], key: str, *, allow_empty: bool = False) -> list[str]:
    values = payload.get(key)
    if not isinstance(values, list) or (not values and not allow_empty):
        qualifier = "an array" if allow_empty else "a non-empty array"
        raise ValueError(f"{key} must be {qualifier}")

    names: list[str] = []
    seen: set[str] = set()
    for value in values:
        if not isinstance(value, str) or not value or value.lower() != value:
            raise ValueError(f"{key} name must be lower-case: {value!r}")
        if value in seen:
            raise ValueError(f"duplicate {key} name: {value}")
        seen.add(value)
        names.append(value)
    return names


def load_catalog(path: Path) -> Catalog:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("CSS property metadata must be an object")
    if payload.get("version") != 1:
        raise ValueError("css property metadata version must be 1")
    managed_known_properties = _load_name_list(payload, "managedKnownProperties")
    supported_property_extras = _load_name_list(
        payload, "supportedPropertyExtras", allow_empty=True)
    entries = payload.get("properties")
    if not isinstance(entries, list) or not entries:
        raise ValueError("properties must be a non-empty array")
    names: set[str] = set()
    known_names = {entry.get("name") for entry in entries if isinstance(entry, dict)}
    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError("each property must be an object")
        name = entry.get("name")
        if not isinstance(name, str) or not name or name.lower() != name:
            raise ValueError(f"property name must be lower-case: {name!r}")
        if name in names:
            raise ValueError(f"duplicate property: {name}")
        names.add(name)
        masks = entry.get("mask")
        if not isinstance(masks, list) or not masks or not all(mask in ALLOWED_MASKS for mask in masks):
            raise ValueError(f"invalid mask list for {name}: {masks!r}")
        alias = entry.get("alias")
        expansion = entry.get("expansion")
        apply_expansion = entry.get("applyExpansion", False)
        if not isinstance(apply_expansion, bool):
            raise ValueError(f"applyExpansion for {name} must be a boolean")
        if alias is not None and expansion is not None:
            raise ValueError(f"{name} cannot define both alias and expansion")
        targets = [alias] if alias is not None else expansion or []
        if alias is not None and not isinstance(alias, str):
            raise ValueError(f"alias for {name} must be a string")
        if expansion is not None and (not isinstance(expansion, list) or len(expansion) not in (2, 4)):
            raise ValueError(f"expansion for {name} must have two or four longhands")
        if apply_expansion and expansion is None:
            raise ValueError(f"{name} applies expansion without defining an expansion")
        for target in targets:
            if target not in known_names:
                raise ValueError(f"{name} references unknown effective property {target!r}")
    return Catalog(
        properties=sorted(entries, key=lambda entry: entry["name"]),
        managed_known_properties=managed_known_properties,
        supported_property_extras=supported_property_extras,
    )


def generate_native(catalog: Catalog) -> str:
    lines = [
        "// Generated by tools/generate_css_property_metadata.py. Do not edit.",
        "inline constexpr std::array effective_property_metadata_catalog{",
    ]
    for entry in catalog.properties:
        targets = ([entry["alias"]] if "alias" in entry else entry.get("expansion", []))
        padded = list(targets) + [""] * (4 - len(targets))
        mask = " | ".join(entry["mask"])
        quoted = ", ".join(f'"{target}"' for target in padded)
        apply_expansion = "true" if entry.get("applyExpansion", False) else "false"
        lines.append(
            f'    effective_property_metadata{{"{entry["name"]}", {mask}, '
            f'{{{quoted}}}, {len(targets)}U, {apply_expansion}}},'
        )
    lines.extend(["};", ""])
    return "\n".join(lines)


def supported_names(catalog: Catalog) -> list[str]:
    return sorted(set(
        catalog.managed_known_properties
        + catalog.supported_property_extras
        + [entry["name"] for entry in catalog.properties]
    ))


def css_idl_name(name: str) -> str:
    if name == "float":
        return "cssFloat"
    parts = name.split("-")
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


def generate_native_supported(catalog: Catalog) -> str:
    lines = [
        "// Generated by tools/generate_css_property_metadata.py. Do not edit.",
        "struct cssom_supported_property_metadata final {",
        "    std::string_view css_name;",
        "    std::string_view idl_name;",
        "};",
        "",
        "inline constexpr std::array cssom_supported_property_catalog{",
    ]
    for name in supported_names(catalog):
        lines.append(
            f'    cssom_supported_property_metadata{{"{name}", "{css_idl_name(name)}"}},')
    lines.extend(["};", ""])
    return "\n".join(lines)


def _append_csharp_array(lines: list[str], name: str, values: list[str]) -> None:
    lines.extend([
        f"    internal static readonly string[] {name} =",
        "    [",
    ])
    for value in values:
        lines.append(f'        "{value}",')
    lines.extend(["    ];", ""])


def generate_managed(catalog: Catalog) -> str:
    lines = [
        "// Generated by tools/generate_css_property_metadata.py. Do not edit.",
        "namespace WebScene.Css;",
        "",
        "internal static class CssGeneratedPropertyMetadata",
        "{",
    ]
    _append_csharp_array(lines, "KnownNames", catalog.managed_known_properties)
    _append_csharp_array(lines, "SupportedNames", supported_names(catalog))
    lines.extend([
        "    internal static bool TryGetKnownId(string name, out int id)",
        "    {",
        "        id = name switch",
        "        {",
    ])
    for index, name in enumerate(catalog.managed_known_properties):
        lines.append(f'            "{name}" => {index},')
    lines.extend([
        "            _ => -1,",
        "        };",
        "        return id >= 0;",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


# Retain the original helper name for callers that only generate the native table.
def generate(catalog: Catalog) -> str:
    return generate_native(catalog)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--native-supported-output", type=Path, default=DEFAULT_NATIVE_SUPPORTED_OUTPUT)
    parser.add_argument("--managed-output", type=Path, default=DEFAULT_MANAGED_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = load_catalog(args.input)
    rendered_native = generate_native(catalog)
    rendered_native_supported = generate_native_supported(catalog)
    rendered_managed = generate_managed(catalog)
    if args.check:
        stale: list[Path] = []
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered_native:
            stale.append(args.output)
        if (not args.native_supported_output.exists()
                or args.native_supported_output.read_text(encoding="utf-8")
                != rendered_native_supported):
            stale.append(args.native_supported_output)
        if (not args.managed_output.exists()
                or args.managed_output.read_text(encoding="utf-8") != rendered_managed):
            stale.append(args.managed_output)
        if stale:
            joined = ", ".join(str(path) for path in stale)
            raise SystemExit(f"stale generated CSS property metadata: {joined}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered_native, encoding="utf-8")
    args.native_supported_output.parent.mkdir(parents=True, exist_ok=True)
    args.native_supported_output.write_text(rendered_native_supported, encoding="utf-8")
    args.managed_output.parent.mkdir(parents=True, exist_ok=True)
    args.managed_output.write_text(rendered_managed, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
